// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwensenAPI.Models
{
    public partial class Product
    {
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string ProductCattagory { get; set; }
    }
}