// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwensenAPI.Models
{
    public partial class Subdistricts
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string NameInThai { get; set; }
        public string NameInEnglish { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int DistrictId { get; set; }
        public string ZipCode { get; set; }

        public virtual Districts District { get; set; }
    }
}