// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwensenAPI.Models
{
    public partial class User
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public DateTime Birthday { get; set; }
    }
}