// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SwensenAPI.Models
{
    public partial class UserAddress
    {
        public int Address_ID { get; set; }
        public string Email { get; set; }
        public string AddressName { get; set; }
        public string Tambon { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
    }
}